# Exported from Render on 2025-01-14T21:50:08Z
services:
- type: web
  name: new-instance-2
  runtime: python
  repo: https://github.com/nekoha0412/new-instance
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn --port $PORT --host 0.0.0.0 main:app
version: "1"
